name: Deploy on master

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Pull code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: [14.x]

    - name: Restore cached node_modules
      uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test

    - name: Deploy
      run: |
        echo "${{secrets.SSH_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
          --exclude /deploy_key \
          --exclude /.git/ \
          --exclude /.github/ \
          --exclude /node_modules/ \
          ./ ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:.
        ssh -i ./deploy_key ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}} sudo update-wordpress-theme
